### ISSUE TITLE
Fix for edit with used or moved items

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#435]
com.avc.mis.beta.service.WarehouseManagement.getAvailableInventory(ItemGroup group, ProductionUse[] productionUses, ProductionFunctionality[] functionalities, 
			Integer itemId, Integer[] poCodeIds, **Integer excludeProcessId**)

I added excludeProcessId so for edit you don't get things that are descendant's of this id.
put the process id overthere (when it's new it will be null). hope it works
use for all processes you are calling for available inventory

**Comment by litzvi** [comment]
pushed in Version: 14.6

**Comment by mei309** [comment]
> com.avc.mis.beta.service.WarehouseManagement.getAvailableInventory(ItemGroup group, ProductionUse[] productionUses, ProductionFunctionality[] functionalities,
> Integer itemId, Integer[] poCodeIds, **Integer excludeProcessId**)
> 
> I added excludeProcessId so for edit you don't get things that are descendant's of this id.
> put the process id overthere (when it's new it will be null). hope it works
> use for all processes you are calling for available inventory

it matters only in reloaction

**Comment by litzvi** [comment]
correct for now but might change

**Comment by litzvi** [comment]
for now relocation is enough

**Comment by mei309** [comment]
its adding the wrong ones

**Comment by mei309** [comment]
its not returning storages that have nothing to do with the process

**Comment by litzvi** [comment]
are those storages a result of a process that is a descendent of this process?
I can't work with a not detailed example because i checked many scenarios already

**Comment by mei309** [comment]
a new raw relocation use only the 317 and not the one and then try edit

**Comment by litzvi** [comment]
fixed. small if error

**Comment by mei309** [comment]
im still getting the storage thats created by the relocation (im filtering by process id and storage id but i think i should only by storage id now that we have the excluding )

**Comment by litzvi** [comment]
You don't need to filter at all. Did you check with a new one? Because I
did a very thorough check for relocation and everything was correct.
So if it happens give me the exact steps or the dump.

**Comment by mei309** [comment]
its working good by the check because im filtering it

**Comment by mei309** [comment]
if you want to see without filtering comment lines 135-138 and 147-148 in relocation-count.component.ts

**Comment by litzvi** [comment]
ok fixed. so only by storage

**Comment by mei309** [comment]
ok done.
